# Generated by Django 6.0.4 on 2026-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alight_many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TModelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'select2_many_to_many_tmodel_test',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tmodel',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
