# Generated by Django 6.0.4 on 2026-05-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alight_many_to_many', '0002_tmodeltest_alter_tmodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tmodel',
            table='select2_many_to_many_tmodel',
        ),
    ]
