[pytest]
addopts = --nomigrations --create-db --reuse-db
DJANGO_SETTINGS_MODULE=settings.base
django_debug_mode=true
filterwarnings =
    ignore::pytest.PytestUnhandledThreadExceptionWarning
    ignore::django.core.paginator.UnorderedObjectListWarning
    ignore:set_timeout\(\) in RemoteConnection is deprecated:DeprecationWarning:pytest_splinter
