# Generated by Django 6.0.4 on 2026-05-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alight_taggit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmodel',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
