# Generated by Django 6.0.4 on 2026-05-04 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alight_linked_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmodel',
            name='group',
        ),
        migrations.AddField(
            model_name='tmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_alight_linked_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tmodel',
            name='for_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='alight_linked_data.tmodel'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterModelOptions(
            name='tmodel',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
