# Generated by Django 6.0.4 on 2026-05-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alight_linked_data', '0002_delete_group_alter_tmodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tmodel',
            table='select2_linked_data_tmodel',
        ),
    ]
