# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='jal_many_to_many.TModel')),
                ('test', models.ManyToManyField(blank=True, null=True, related_name='_tmodel_test_+', to='jal_many_to_many.TModel')),
            ],
        ),
    ]
