# Generated by Django 6.0.4 on 2026-04-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alight_tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmodel',
            name='name',
        ),
    ]
