# Generated by Django 2.0.6 on 2018-06-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='select2_many_to_many.TModel')),
                ('test', models.ManyToManyField(blank=True, related_name='_tmodel_test_+', to='select2_many_to_many.TModel')),
            ],
        ),
    ]
