# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select2_generic_foreign_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_test_models', to='contenttypes.ContentType'),
        ),
    ]
