# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'MasterModel',
            },
        ),
        migrations.CreateModel(
            name='ModelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ModelOne',
            },
        ),
        migrations.CreateModel(
            name='ModelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ModelTwo',
            },
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='modelone',
            field=models.ManyToManyField(blank=True, to='select2_outside_admin_multiple.ModelOne', verbose_name='ModelOne'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='modeltwo',
            field=models.ManyToManyField(blank=True, to='select2_outside_admin_multiple.ModelTwo', verbose_name='ModelTwo'),
        ),
    ]
