# Generated by Django 6.0.4 on 2026-05-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alight_list', '0002_remove_tmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmodel',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
