# Generated by Django 6.0.4 on 2026-05-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alight_list', '0005_restore_own_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmodel',
            name='for_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='alight_list.tmodel'),
        ),
        migrations.AlterField(
            model_name='tmodel',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
