# Generated by Django 6.0.4 on 2026-05-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alight_nestedadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmodelone',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tmodelthree',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tmodeltwo',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
